version: "3.9"
services:
  acquaount-platform:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/main/:/usr/src/app/src/main
    ports:
      - "80:80"
    depends_on:
      - sensorthings-api

  acquaount-data-integration:
    build:
      context: src/resources/dataIntegration/
      dockerfile: Dockerfile
    volumes:
      - ./src/resources/dataIntegration/logs/:/logs/
      - ./src/resources/modelService/dk/results/:/modelData/
    depends_on:
      - acquaount-platform
    environment:
      - PYTHONUNBUFFERED=1

  sensorthings-api:
    image: fraunhoferiosb/frost-server:2.0
    environment:
      - serviceRootUrl=http://localhost:8008/FROST-Server
      - plugins.multiDatastream.enable=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database-gis:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8008:8080
      - 1883:1883
    depends_on:
      database-gis:
        condition: "service_healthy"

  database-gis:
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - ./src/resources/db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--host=database-gis", "--port=5432", "--username=sensorthings" ]
      interval: 15s
      timeout: 30s
      retries: 40
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 4g
