services:
  model:
    build: .
    image: model_acquaount_irr:2.0.0
    volumes:
      - ./data/:/data/
      - ./run.json:/run.json
      - ./apikey.txt:/apikey.txt
      - ./weather-apikey.txt:/weather-apikey.txt 
      - ./config.input.json:/config.input.json
