services:
  batch:
    build:
      context: ../dk
      dockerfile: Dockerfile
    volumes:
      - results:/dk/HMS_Tirso_v2/results
    restart: on-failure

  api: 
    build:
      context: ../model_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - results:/app/data/results
    environment:
      - ENVIRONMENT=development

volumes: 
  results: